default: &default
  adapter: postgresql
  encoding: unicode
  username: ivan
  pool: 5

production:
  <<: *default
  database: book_production
  template: template0

development:
  <<: *default
  database: book_development
  template: template0

test:
  <<: *default
  database: book_test
  template: template0